spring.application.name=bookmarkmanager
spring.datasource.url=jdbc:postgresql://localhost:5433/bookmarks
spring.datasource.username=postgres
spring.datasource.password=example
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
